theme: jekyll-theme-cayman

title:        KOO APP技术支持
description:      年轻就是要KOO！
show_downloads: false

github:
  is_project_page: false

# About/contact
author:
  name:      kooapp
  email:     qubo.qin.2018@gmail.com
  github:    kooapp
  url:       http://kooapp.github.io
